//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Action Maps/InputActionMaps.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActionMaps : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActionMaps()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActionMaps"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""4c6d7842-9629-4e43-9adc-c302cf96bb6f"",
            ""actions"": [
                {
                    ""name"": ""Slider"",
                    ""type"": ""Button"",
                    ""id"": ""d1d79634-f33b-49aa-bbee-6967f61e4046"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetSlider"",
                    ""type"": ""Button"",
                    ""id"": ""56821f1b-7936-4d19-a623-7e8b88f9a967"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""107a5644-fbb9-4864-acd6-a17ef0027606"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slider"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f2b7506-6669-48f3-a703-b8810289b9bc"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetSlider"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Slider = m_Player.FindAction("Slider", throwIfNotFound: true);
        m_Player_ResetSlider = m_Player.FindAction("ResetSlider", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Slider;
    private readonly InputAction m_Player_ResetSlider;
    public struct PlayerActions
    {
        private @InputActionMaps m_Wrapper;
        public PlayerActions(@InputActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Slider => m_Wrapper.m_Player_Slider;
        public InputAction @ResetSlider => m_Wrapper.m_Player_ResetSlider;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Slider.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSlider;
                @Slider.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSlider;
                @Slider.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSlider;
                @ResetSlider.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnResetSlider;
                @ResetSlider.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnResetSlider;
                @ResetSlider.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnResetSlider;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Slider.started += instance.OnSlider;
                @Slider.performed += instance.OnSlider;
                @Slider.canceled += instance.OnSlider;
                @ResetSlider.started += instance.OnResetSlider;
                @ResetSlider.performed += instance.OnResetSlider;
                @ResetSlider.canceled += instance.OnResetSlider;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnSlider(InputAction.CallbackContext context);
        void OnResetSlider(InputAction.CallbackContext context);
    }
}
